name: Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Scan requirements
        # Añadimos la ruta correcta al archivo
        run: pip-audit -r sportsclub-main/requirements.txt
